Add files via upload

diff --git a/Rocknet b/Rocknet
--- a/Rocknet
+++ b/Rocknet
@@ -4,15 +4,10 @@ clear
 echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33mAnda harus login sebagai root\033[0m"
 rm $HOME/Plus > /dev/null 2>&1; exit 0
 }
-_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
+_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 cd $HOME
-GitUser="https://raw.githubusercontent.com/rockneters/jancuk/main"
-cd $HOME
-echo "Update & Install Aplikasi Pendukung..."
-sleep 1s
-apt update -y; apt upgrade -y; apt install wget curl
-
-#Loading animasi----------------------------------------
 fun_bar () {
 comando[0]="$1"
 comando[1]="$2"
@@ -39,7 +34,15 @@ done
 echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
 tput cnorm
 }
-
+function verif_key () {
+krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
+[[ ! -e "$_Ink/list" ]] && {
+  echo -e "\n\033[1;31mINVALID KEY!\033[0m"
+  rm -rf $HOME/Plus > /dev/null 2>&1
+  sleep 2
+  clear; exit 1
+}
+}
 
 #Header----------------------------------------------------
 clear
@@ -61,11 +64,19 @@ read -p "$(echo -e "\033[1;36mAPAKAH INGIN MELANJUTKAN ? \033[1;33m[y/N]:\033[0m
 cp /etc/ssh/sshd_config /etc/ssh/sshd_back
 wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/rockneters/jancuk/main/module/sshd_config > /dev/null 2>&1
 service ssh restart  > /dev/null 2>&1
-echo -e "\033[1;36mChecking Permission....\033[0m" 
+echo -e "\033[1;36mChecking Permission....\033[0m"
+rm $_Ink/list > /dev/null 2>&1
+wget -P $_Ink https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/list > /dev/null 2>&1
+verif_key
 sleep 3s
 echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
-echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/rockneters/jancuk/main/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus; chmod +x /bin/sshplus > /dev/null 2>&1
+echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/rockneters/jancuk/main/Rocknet; chmod 777 Rocknet; ./Rocknet" > /bin/sshplus; chmod +x /bin/sshplus > /dev/null 2>&1
 wget -O /bin/menu https://raw.githubusercontent.com/rockneters/jancuk/main/module/menu > /dev/null 2>&1; chmod +x /bin/menu
+wget -O /bin/menuV1 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV1 > /dev/null 2>&1; chmod +x /bin/menuV1
+wget -O /bin/menuV2 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV2 > /dev/null 2>&1; chmod +x /bin/menuV2
+wget -O /bin/menuV3 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV3 > /dev/null 2>&1; chmod +x /bin/menuV3
+wget -O /bin/menuV4 https://raw.githubusercontent.com/rockneters/jancuk/main/module/menuV4 > /dev/null 2>&1; chmod +x /bin/menuV4
+rm versao* > /dev/null 2>&1; wget https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/versao > /dev/null 2>&1
 clear
 
 #Database------------------------------------------------------------------------
@@ -120,18 +131,18 @@ echo -e "\033[1;33m[!] \033[1;32mINSTALL ALL SERVICE \033[1;33m[!]\033[0m"
 echo -e "\033[1;33m===-TUNGGULAH SAMPAI 5-10 MENIT!-=== \033[0m"
 echo ""
 sleep 5
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ssh-vpn.sh; chmod +x ssh-vpn.sh; screen -S ssh-vpn ./ssh-vpn.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssr.sh; chmod +x ins-ssr.sh; screen -S ins-ssr ./ins-ssr.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-sstp.sh; chmod +x ins-sstp.sh; screen -S ins-sstp ./ins-sstp.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-tcptweaker.sh; chmod +x ins-tcptweaker.sh; screen -S ins-tcptweaker ./ins-tcptweaker.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-webmin.sh; chmod +x ins-webmin.sh; screen -S ins-webmin ./ins-webmin.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-vt.sh; chmod +x ins-vt.sh; screen -S ins-vt ./ins-vt.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-wg.sh; chmod +x ins-wg.sh; screen -S ins-wg ./ins-wg.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-badvpn.sh; chmod +x ins-badvpn.sh; screen -S ins-badvpn ./ins-badvpn.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-go.sh; chmod +x ins-go.sh; screen -S ins-go ./ins-go.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ipsec.sh; chmod +x ins-ipsec.sh; screen -S ins-ipsec ./ins-ipsec.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssobfs.sh; chmod +x ins-ssobfs.sh; screen -S ins-ssobfs ./ins-ssobfs.sh
-wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-menu.sh; chmod +x ins-menu.sh; screen -S ins-menu ./ins-menu.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ssh-vpn.sh; chmod +x ssh-vpn.sh; ./ssh-vpn.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-vt.sh; chmod +x ins-vt.sh; ./ins-vt.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssr.sh; chmod +x ins-ssr.sh; ./ins-ssr.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-sstp.sh; chmod +x ins-sstp.sh; ./ins-sstp.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-tcptweaker.sh; chmod +x ins-tcptweaker.sh; ./ins-tcptweaker.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-webmin.sh; chmod +x ins-webmin.sh; ./ins-webmin.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-wg.sh; chmod +x ins-wg.sh; ./ins-wg.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-badvpn.sh; chmod +x ins-badvpn.sh; ./ins-badvpn.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-go.sh; chmod +x ins-go.sh; ./ins-go.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ipsec.sh; chmod +x ins-ipsec.sh; ./ins-ipsec.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-ssobfs.sh; chmod +x ins-ssobfs.sh; ./ins-ssobfs.sh
+wget https://raw.githubusercontent.com/rockneters/jancuk/main/install/ins-menu.sh; chmod +x ins-menu.sh; ./ins-menu.sh
 
 clear
 echo -e "\033[1;33m[!] \033[1;32mFINISHING \033[1;33m[!]\033[0m"
@@ -146,3 +157,4 @@ echo ""
 echo -e "\033[1;31m \033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"
 echo ""
 rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
+rm ssh-vpn.sh ins-ssr.sh ins-sstp.sh ins-tcptweaker.sh ins-webmin.sh ins-vt.sh ins-wg.sh ins-badvpn.sh ins-go.sh ins-ipsec.sh ins-ssobfs.sh ins-menu.sh
