Add files via upload

diff --git a/module/botssh b/module/botssh
--- a/module/botssh
+++ b/module/botssh
@@ -30,14 +30,14 @@ tput cnorm
 fun_botOnOff () {
       [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) = '0' ]] && {
           clear
-          echo -e "\E[44;1;37m             BOT ROCKNETSSH INSTALLER                \E[0m\n"
+          echo -e "\E[44;1;37m             BOT DARKSSH INSTALLER                \E[0m\n"
           echo -ne "\033[1;32mINFORM YOUR TOKEN:\033[1;37m "; read tokenbot
   	    echo ""
   	    echo -ne "\033[1;32mINFORM YOUR ID:\033[1;37m "; read iduser
           clear
-          echo -e "\033[1;32mSTARTING ROCKNETSSH BOT \033[0m\n"
+          echo -e "\033[1;32mSTARTING DARKSSH BOT \033[0m\n"
           fun_bot1 () {
-  	        [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/rockneters/jalingkut/Install/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
+  	        [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
   	        cd /etc/SSHPlus
   	        screen -dmS bot_plus ./bot $tokenbot $iduser > /dev/null 2>&1
               [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
@@ -50,12 +50,12 @@ fun_botOnOff () {
   	        cd $HOME
           }
           fun_bar 'fun_bot1'
-          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m ROCKNETSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YouR INFORMATION\033[0m"
+          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m DARKSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
           sleep 3
           menu
       } || {
           clear
-          echo -e "\033[1;32mSTOPPING BOT ROCKNETSSH ... \033[0m\n"
+          echo -e "\033[1;32mSTOPPING BOT DARKSSH ... \033[0m\n"
           fun_bot2 () {
               screen -r -S "bot_plus" -X quit
               screen -wipe 1>/dev/null 2>/dev/null
@@ -66,7 +66,7 @@ fun_botOnOff () {
               sleep 1
           }
           fun_bar 'fun_bot2'
-          echo -e "\n\033[1;32m \033[1;31mROCKNETSSH BOT STOPPED! \033[0m"
+          echo -e "\n\033[1;32m \033[1;31mDARKSSH BOT STOPPED! \033[0m"
           sleep 3
           menu
       }
@@ -80,7 +80,7 @@ echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;3
 echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@my_id_bot \033[1;33mAND GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
 echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
 echo ""
-read -p "DO YOU WISH TO CONTINUE ? [s/n]: " -e -i n resposta
+read -p "DESEJA CONTINUAR ? [s/n]: " -e -i n resposta
 if [[ "$resposta" = 's' ]]; then
   	fun_botOnOff
   else
